// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medicine.sql

package db

import (
	"context"
	"database/sql"
)

const countMedicines = `-- name: CountMedicines :one
SELECT count(*) FROM medicines
`

func (q *Queries) CountMedicines(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMedicines)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedicine = `-- name: CreateMedicine :one
INSERT INTO medicines (
  name,
  unit,
  price,
  stock,
  description
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, unit, price, stock, description, created_at, updated_at
`

type CreateMedicineParams struct {
	Name        string         `json:"name"`
	Unit        interface{}    `json:"unit"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateMedicine(ctx context.Context, arg CreateMedicineParams) (Medicine, error) {
	row := q.db.QueryRowContext(ctx, createMedicine,
		arg.Name,
		arg.Unit,
		arg.Price,
		arg.Stock,
		arg.Description,
	)
	var i Medicine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedicine = `-- name: DeleteMedicine :exec
DELETE FROM medicines
WHERE id = $1
`

func (q *Queries) DeleteMedicine(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMedicine, id)
	return err
}

const getMedicine = `-- name: GetMedicine :one
SELECT id, name, unit, price, stock, description, created_at, updated_at FROM medicines
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMedicine(ctx context.Context, id int32) (Medicine, error) {
	row := q.db.QueryRowContext(ctx, getMedicine, id)
	var i Medicine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedicines = `-- name: ListMedicines :many
SELECT id, name, unit, price, stock, description, created_at, updated_at FROM medicines
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListMedicinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMedicines(ctx context.Context, arg ListMedicinesParams) ([]Medicine, error) {
	rows, err := q.db.QueryContext(ctx, listMedicines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medicine{}
	for rows.Next() {
		var i Medicine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.Price,
			&i.Stock,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedicine = `-- name: UpdateMedicine :one
UPDATE medicines
SET
  name = COALESCE($1, name),
  unit = COALESCE($2, unit),
  price = COALESCE($3, price),
  stock = COALESCE($4, stock),
  description = COALESCE($5, description),
  updated_at = now()
WHERE id = $6
RETURNING id, name, unit, price, stock, description, created_at, updated_at
`

type UpdateMedicineParams struct {
	Name        sql.NullString `json:"name"`
	Unit        interface{}    `json:"unit"`
	Price       sql.NullString `json:"price"`
	Stock       sql.NullInt32  `json:"stock"`
	Description sql.NullString `json:"description"`
	ID          int32          `json:"id"`
}

func (q *Queries) UpdateMedicine(ctx context.Context, arg UpdateMedicineParams) (Medicine, error) {
	row := q.db.QueryRowContext(ctx, updateMedicine,
		arg.Name,
		arg.Unit,
		arg.Price,
		arg.Stock,
		arg.Description,
		arg.ID,
	)
	var i Medicine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
