// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_role.sql

package db

import (
	"context"
)

const addRoleForUser = `-- name: AddRoleForUser :one
INSERT INTO user_roles (
  user_id,
  role_id
) VALUES (
  $1, $2
) RETURNING user_id, role_id, created_at, updated_at
`

type AddRoleForUserParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) AddRoleForUser(ctx context.Context, arg AddRoleForUserParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, addRoleForUser, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUserRoles = `-- name: CountUserRoles :one
SELECT count(*) FROM user_roles
`

func (q *Queries) CountUserRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRolesForUser = `-- name: GetRolesForUser :many
SELECT roles.id, roles.name, roles.description, roles.created_at, roles.updated_at FROM roles
JOIN user_roles ON roles.id = user_roles.role_id
WHERE user_roles.user_id = $1
`

func (q *Queries) GetRolesForUser(ctx context.Context, userID int32) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT user_id, role_id, created_at, updated_at FROM user_roles
ORDER BY user_id, role_id
LIMIT $1
OFFSET $2
`

type ListUserRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleForUser = `-- name: RemoveRoleForUser :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleForUserParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) RemoveRoleForUser(ctx context.Context, arg RemoveRoleForUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleForUser, arg.UserID, arg.RoleID)
	return err
}
