// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/toannguyen3105/nht-socmanga.com-api/db/sqlc (interfaces: Store)

// Package mock_sqlc is a generated GoMock package.
package mock_sqlc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/toannguyen3105/nht-socmanga.com-api/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddAccountBalance mocks base method.
func (m *MockStore) AddAccountBalance(arg0 context.Context, arg1 db.AddAccountBalanceParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountBalance", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAccountBalance indicates an expected call of AddAccountBalance.
func (mr *MockStoreMockRecorder) AddAccountBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccountBalance", reflect.TypeOf((*MockStore)(nil).AddAccountBalance), arg0, arg1)
}

// CountComics mocks base method.
func (m *MockStore) CountComics(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountComics", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountComics indicates an expected call of CountComics.
func (mr *MockStoreMockRecorder) CountComics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountComics", reflect.TypeOf((*MockStore)(nil).CountComics), arg0)
}

// CountTrendingComics mocks base method.
func (m *MockStore) CountTrendingComics(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTrendingComics", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTrendingComics indicates an expected call of CountTrendingComics.
func (mr *MockStoreMockRecorder) CountTrendingComics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTrendingComics", reflect.TypeOf((*MockStore)(nil).CountTrendingComics), arg0)
}

// CreateAccount mocks base method.
func (m *MockStore) CreateAccount(arg0 context.Context, arg1 db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStoreMockRecorder) CreateAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStore)(nil).CreateAccount), arg0, arg1)
}

// CreateChapter mocks base method.
func (m *MockStore) CreateChapter(arg0 context.Context, arg1 db.CreateChapterParams) (db.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChapter", arg0, arg1)
	ret0, _ := ret[0].(db.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChapter indicates an expected call of CreateChapter.
func (mr *MockStoreMockRecorder) CreateChapter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChapter", reflect.TypeOf((*MockStore)(nil).CreateChapter), arg0, arg1)
}

// CreateChapterComment mocks base method.
func (m *MockStore) CreateChapterComment(arg0 context.Context, arg1 db.CreateChapterCommentParams) (db.ChapterComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChapterComment", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChapterComment indicates an expected call of CreateChapterComment.
func (mr *MockStoreMockRecorder) CreateChapterComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChapterComment", reflect.TypeOf((*MockStore)(nil).CreateChapterComment), arg0, arg1)
}

// CreateChapterImage mocks base method.
func (m *MockStore) CreateChapterImage(arg0 context.Context, arg1 db.CreateChapterImageParams) (db.ChapterImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChapterImage", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChapterImage indicates an expected call of CreateChapterImage.
func (mr *MockStoreMockRecorder) CreateChapterImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChapterImage", reflect.TypeOf((*MockStore)(nil).CreateChapterImage), arg0, arg1)
}

// CreateChapterLike mocks base method.
func (m *MockStore) CreateChapterLike(arg0 context.Context, arg1 db.CreateChapterLikeParams) (db.ChapterLike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChapterLike", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterLike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChapterLike indicates an expected call of CreateChapterLike.
func (mr *MockStoreMockRecorder) CreateChapterLike(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChapterLike", reflect.TypeOf((*MockStore)(nil).CreateChapterLike), arg0, arg1)
}

// CreateComic mocks base method.
func (m *MockStore) CreateComic(arg0 context.Context, arg1 db.CreateComicParams) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComic", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComic indicates an expected call of CreateComic.
func (mr *MockStoreMockRecorder) CreateComic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComic", reflect.TypeOf((*MockStore)(nil).CreateComic), arg0, arg1)
}

// CreateComicFollow mocks base method.
func (m *MockStore) CreateComicFollow(arg0 context.Context, arg1 db.CreateComicFollowParams) (db.ComicFollow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComicFollow", arg0, arg1)
	ret0, _ := ret[0].(db.ComicFollow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComicFollow indicates an expected call of CreateComicFollow.
func (mr *MockStoreMockRecorder) CreateComicFollow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComicFollow", reflect.TypeOf((*MockStore)(nil).CreateComicFollow), arg0, arg1)
}

// CreateComicView mocks base method.
func (m *MockStore) CreateComicView(arg0 context.Context, arg1 db.CreateComicViewParams) (db.ComicView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComicView", arg0, arg1)
	ret0, _ := ret[0].(db.ComicView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComicView indicates an expected call of CreateComicView.
func (mr *MockStoreMockRecorder) CreateComicView(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComicView", reflect.TypeOf((*MockStore)(nil).CreateComicView), arg0, arg1)
}

// CreateEntry mocks base method.
func (m *MockStore) CreateEntry(arg0 context.Context, arg1 db.CreateEntryParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntry", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntry indicates an expected call of CreateEntry.
func (mr *MockStoreMockRecorder) CreateEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockStore)(nil).CreateEntry), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateTransfer mocks base method.
func (m *MockStore) CreateTransfer(arg0 context.Context, arg1 db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockStoreMockRecorder) CreateTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockStore)(nil).CreateTransfer), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// DeleteAccount mocks base method.
func (m *MockStore) DeleteAccount(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockStoreMockRecorder) DeleteAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockStore)(nil).DeleteAccount), arg0, arg1)
}

// DeleteChapter mocks base method.
func (m *MockStore) DeleteChapter(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChapter", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChapter indicates an expected call of DeleteChapter.
func (mr *MockStoreMockRecorder) DeleteChapter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChapter", reflect.TypeOf((*MockStore)(nil).DeleteChapter), arg0, arg1)
}

// DeleteChapterComment mocks base method.
func (m *MockStore) DeleteChapterComment(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChapterComment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChapterComment indicates an expected call of DeleteChapterComment.
func (mr *MockStoreMockRecorder) DeleteChapterComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChapterComment", reflect.TypeOf((*MockStore)(nil).DeleteChapterComment), arg0, arg1)
}

// DeleteChapterImage mocks base method.
func (m *MockStore) DeleteChapterImage(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChapterImage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChapterImage indicates an expected call of DeleteChapterImage.
func (mr *MockStoreMockRecorder) DeleteChapterImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChapterImage", reflect.TypeOf((*MockStore)(nil).DeleteChapterImage), arg0, arg1)
}

// DeleteChapterLike mocks base method.
func (m *MockStore) DeleteChapterLike(arg0 context.Context, arg1 db.DeleteChapterLikeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChapterLike", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChapterLike indicates an expected call of DeleteChapterLike.
func (mr *MockStoreMockRecorder) DeleteChapterLike(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChapterLike", reflect.TypeOf((*MockStore)(nil).DeleteChapterLike), arg0, arg1)
}

// DeleteComic mocks base method.
func (m *MockStore) DeleteComic(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComic indicates an expected call of DeleteComic.
func (mr *MockStoreMockRecorder) DeleteComic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComic", reflect.TypeOf((*MockStore)(nil).DeleteComic), arg0, arg1)
}

// DeleteComicFollow mocks base method.
func (m *MockStore) DeleteComicFollow(arg0 context.Context, arg1 db.DeleteComicFollowParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComicFollow", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComicFollow indicates an expected call of DeleteComicFollow.
func (mr *MockStoreMockRecorder) DeleteComicFollow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComicFollow", reflect.TypeOf((*MockStore)(nil).DeleteComicFollow), arg0, arg1)
}

// DeleteEntry mocks base method.
func (m *MockStore) DeleteEntry(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockStoreMockRecorder) DeleteEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockStore)(nil).DeleteEntry), arg0, arg1)
}

// DeleteTransfer mocks base method.
func (m *MockStore) DeleteTransfer(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransfer indicates an expected call of DeleteTransfer.
func (mr *MockStoreMockRecorder) DeleteTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransfer", reflect.TypeOf((*MockStore)(nil).DeleteTransfer), arg0, arg1)
}

// GetAccount mocks base method.
func (m *MockStore) GetAccount(arg0 context.Context, arg1 int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockStoreMockRecorder) GetAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockStore)(nil).GetAccount), arg0, arg1)
}

// GetAccountForUpdate mocks base method.
func (m *MockStore) GetAccountForUpdate(arg0 context.Context, arg1 int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountForUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountForUpdate indicates an expected call of GetAccountForUpdate.
func (mr *MockStoreMockRecorder) GetAccountForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountForUpdate", reflect.TypeOf((*MockStore)(nil).GetAccountForUpdate), arg0, arg1)
}

// GetChapter mocks base method.
func (m *MockStore) GetChapter(arg0 context.Context, arg1 int64) (db.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChapter", arg0, arg1)
	ret0, _ := ret[0].(db.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChapter indicates an expected call of GetChapter.
func (mr *MockStoreMockRecorder) GetChapter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChapter", reflect.TypeOf((*MockStore)(nil).GetChapter), arg0, arg1)
}

// GetChapterByComicIDAndNumber mocks base method.
func (m *MockStore) GetChapterByComicIDAndNumber(arg0 context.Context, arg1 db.GetChapterByComicIDAndNumberParams) (db.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChapterByComicIDAndNumber", arg0, arg1)
	ret0, _ := ret[0].(db.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChapterByComicIDAndNumber indicates an expected call of GetChapterByComicIDAndNumber.
func (mr *MockStoreMockRecorder) GetChapterByComicIDAndNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChapterByComicIDAndNumber", reflect.TypeOf((*MockStore)(nil).GetChapterByComicIDAndNumber), arg0, arg1)
}

// GetChapterComment mocks base method.
func (m *MockStore) GetChapterComment(arg0 context.Context, arg1 int64) (db.ChapterComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChapterComment", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChapterComment indicates an expected call of GetChapterComment.
func (mr *MockStoreMockRecorder) GetChapterComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChapterComment", reflect.TypeOf((*MockStore)(nil).GetChapterComment), arg0, arg1)
}

// GetChapterImage mocks base method.
func (m *MockStore) GetChapterImage(arg0 context.Context, arg1 int64) (db.ChapterImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChapterImage", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChapterImage indicates an expected call of GetChapterImage.
func (mr *MockStoreMockRecorder) GetChapterImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChapterImage", reflect.TypeOf((*MockStore)(nil).GetChapterImage), arg0, arg1)
}

// GetComic mocks base method.
func (m *MockStore) GetComic(arg0 context.Context, arg1 int64) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComic", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComic indicates an expected call of GetComic.
func (mr *MockStoreMockRecorder) GetComic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComic", reflect.TypeOf((*MockStore)(nil).GetComic), arg0, arg1)
}

// GetComicBySlug mocks base method.
func (m *MockStore) GetComicBySlug(arg0 context.Context, arg1 string) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicBySlug", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicBySlug indicates an expected call of GetComicBySlug.
func (mr *MockStoreMockRecorder) GetComicBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicBySlug", reflect.TypeOf((*MockStore)(nil).GetComicBySlug), arg0, arg1)
}

// GetComicByTitle mocks base method.
func (m *MockStore) GetComicByTitle(arg0 context.Context, arg1 string) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicByTitle", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicByTitle indicates an expected call of GetComicByTitle.
func (mr *MockStoreMockRecorder) GetComicByTitle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicByTitle", reflect.TypeOf((*MockStore)(nil).GetComicByTitle), arg0, arg1)
}

// GetComicDetail mocks base method.
func (m *MockStore) GetComicDetail(arg0 context.Context, arg1 string) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicDetail", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicDetail indicates an expected call of GetComicDetail.
func (mr *MockStoreMockRecorder) GetComicDetail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicDetail", reflect.TypeOf((*MockStore)(nil).GetComicDetail), arg0, arg1)
}

// GetEntry mocks base method.
func (m *MockStore) GetEntry(arg0 context.Context, arg1 int64) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockStoreMockRecorder) GetEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockStore)(nil).GetEntry), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// GetTransfer mocks base method.
func (m *MockStore) GetTransfer(arg0 context.Context, arg1 int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransfer indicates an expected call of GetTransfer.
func (mr *MockStoreMockRecorder) GetTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransfer", reflect.TypeOf((*MockStore)(nil).GetTransfer), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// ListAccounts mocks base method.
func (m *MockStore) ListAccounts(arg0 context.Context, arg1 db.ListAccountsParams) ([]db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", arg0, arg1)
	ret0, _ := ret[0].([]db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockStoreMockRecorder) ListAccounts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockStore)(nil).ListAccounts), arg0, arg1)
}

// ListChapterComments mocks base method.
func (m *MockStore) ListChapterComments(arg0 context.Context, arg1 int64) ([]db.ChapterComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChapterComments", arg0, arg1)
	ret0, _ := ret[0].([]db.ChapterComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChapterComments indicates an expected call of ListChapterComments.
func (mr *MockStoreMockRecorder) ListChapterComments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChapterComments", reflect.TypeOf((*MockStore)(nil).ListChapterComments), arg0, arg1)
}

// ListChapterImages mocks base method.
func (m *MockStore) ListChapterImages(arg0 context.Context, arg1 int64) ([]db.ChapterImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChapterImages", arg0, arg1)
	ret0, _ := ret[0].([]db.ChapterImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChapterImages indicates an expected call of ListChapterImages.
func (mr *MockStoreMockRecorder) ListChapterImages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChapterImages", reflect.TypeOf((*MockStore)(nil).ListChapterImages), arg0, arg1)
}

// ListChapters mocks base method.
func (m *MockStore) ListChapters(arg0 context.Context, arg1 db.ListChaptersParams) ([]db.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChapters", arg0, arg1)
	ret0, _ := ret[0].([]db.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChapters indicates an expected call of ListChapters.
func (mr *MockStoreMockRecorder) ListChapters(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChapters", reflect.TypeOf((*MockStore)(nil).ListChapters), arg0, arg1)
}

// ListChaptersByComicID mocks base method.
func (m *MockStore) ListChaptersByComicID(arg0 context.Context, arg1 int64) ([]db.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChaptersByComicID", arg0, arg1)
	ret0, _ := ret[0].([]db.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChaptersByComicID indicates an expected call of ListChaptersByComicID.
func (mr *MockStoreMockRecorder) ListChaptersByComicID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChaptersByComicID", reflect.TypeOf((*MockStore)(nil).ListChaptersByComicID), arg0, arg1)
}

// ListComics mocks base method.
func (m *MockStore) ListComics(arg0 context.Context, arg1 db.ListComicsParams) ([]db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComics", arg0, arg1)
	ret0, _ := ret[0].([]db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComics indicates an expected call of ListComics.
func (mr *MockStoreMockRecorder) ListComics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComics", reflect.TypeOf((*MockStore)(nil).ListComics), arg0, arg1)
}

// ListComicsByUpdatedAtAsc mocks base method.
func (m *MockStore) ListComicsByUpdatedAtAsc(arg0 context.Context, arg1 db.ListComicsByUpdatedAtAscParams) ([]db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComicsByUpdatedAtAsc", arg0, arg1)
	ret0, _ := ret[0].([]db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComicsByUpdatedAtAsc indicates an expected call of ListComicsByUpdatedAtAsc.
func (mr *MockStoreMockRecorder) ListComicsByUpdatedAtAsc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComicsByUpdatedAtAsc", reflect.TypeOf((*MockStore)(nil).ListComicsByUpdatedAtAsc), arg0, arg1)
}

// ListComicsByUpdatedAtDesc mocks base method.
func (m *MockStore) ListComicsByUpdatedAtDesc(arg0 context.Context, arg1 db.ListComicsByUpdatedAtDescParams) ([]db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComicsByUpdatedAtDesc", arg0, arg1)
	ret0, _ := ret[0].([]db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComicsByUpdatedAtDesc indicates an expected call of ListComicsByUpdatedAtDesc.
func (mr *MockStoreMockRecorder) ListComicsByUpdatedAtDesc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComicsByUpdatedAtDesc", reflect.TypeOf((*MockStore)(nil).ListComicsByUpdatedAtDesc), arg0, arg1)
}

// ListEntries mocks base method.
func (m *MockStore) ListEntries(arg0 context.Context, arg1 db.ListEntriesParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", arg0, arg1)
	ret0, _ := ret[0].([]db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockStoreMockRecorder) ListEntries(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockStore)(nil).ListEntries), arg0, arg1)
}

// ListTransfers mocks base method.
func (m *MockStore) ListTransfers(arg0 context.Context, arg1 db.ListTransfersParams) ([]db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfers", arg0, arg1)
	ret0, _ := ret[0].([]db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransfers indicates an expected call of ListTransfers.
func (mr *MockStoreMockRecorder) ListTransfers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransfers", reflect.TypeOf((*MockStore)(nil).ListTransfers), arg0, arg1)
}

// ListTrendingComics mocks base method.
func (m *MockStore) ListTrendingComics(arg0 context.Context, arg1 db.ListTrendingComicsParams) ([]db.ListTrendingComicsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrendingComics", arg0, arg1)
	ret0, _ := ret[0].([]db.ListTrendingComicsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrendingComics indicates an expected call of ListTrendingComics.
func (mr *MockStoreMockRecorder) ListTrendingComics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrendingComics", reflect.TypeOf((*MockStore)(nil).ListTrendingComics), arg0, arg1)
}

// TransferTx mocks base method.
func (m *MockStore) TransferTx(arg0 context.Context, arg1 db.TransferTxParams) (db.TransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTx", arg0, arg1)
	ret0, _ := ret[0].(db.TransferTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferTx indicates an expected call of TransferTx.
func (mr *MockStoreMockRecorder) TransferTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTx", reflect.TypeOf((*MockStore)(nil).TransferTx), arg0, arg1)
}

// UpdateAccount mocks base method.
func (m *MockStore) UpdateAccount(arg0 context.Context, arg1 db.UpdateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockStoreMockRecorder) UpdateAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockStore)(nil).UpdateAccount), arg0, arg1)
}

// UpdateChapter mocks base method.
func (m *MockStore) UpdateChapter(arg0 context.Context, arg1 db.UpdateChapterParams) (db.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChapter", arg0, arg1)
	ret0, _ := ret[0].(db.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChapter indicates an expected call of UpdateChapter.
func (mr *MockStoreMockRecorder) UpdateChapter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChapter", reflect.TypeOf((*MockStore)(nil).UpdateChapter), arg0, arg1)
}

// UpdateChapterComment mocks base method.
func (m *MockStore) UpdateChapterComment(arg0 context.Context, arg1 db.UpdateChapterCommentParams) (db.ChapterComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChapterComment", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChapterComment indicates an expected call of UpdateChapterComment.
func (mr *MockStoreMockRecorder) UpdateChapterComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChapterComment", reflect.TypeOf((*MockStore)(nil).UpdateChapterComment), arg0, arg1)
}

// UpdateChapterImage mocks base method.
func (m *MockStore) UpdateChapterImage(arg0 context.Context, arg1 db.UpdateChapterImageParams) (db.ChapterImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChapterImage", arg0, arg1)
	ret0, _ := ret[0].(db.ChapterImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChapterImage indicates an expected call of UpdateChapterImage.
func (mr *MockStoreMockRecorder) UpdateChapterImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChapterImage", reflect.TypeOf((*MockStore)(nil).UpdateChapterImage), arg0, arg1)
}

// UpdateComic mocks base method.
func (m *MockStore) UpdateComic(arg0 context.Context, arg1 db.UpdateComicParams) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComic", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComic indicates an expected call of UpdateComic.
func (mr *MockStoreMockRecorder) UpdateComic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComic", reflect.TypeOf((*MockStore)(nil).UpdateComic), arg0, arg1)
}

// UpdateEntry mocks base method.
func (m *MockStore) UpdateEntry(arg0 context.Context, arg1 db.UpdateEntryParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntry", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEntry indicates an expected call of UpdateEntry.
func (mr *MockStoreMockRecorder) UpdateEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockStore)(nil).UpdateEntry), arg0, arg1)
}

// UpdateTransfer mocks base method.
func (m *MockStore) UpdateTransfer(arg0 context.Context, arg1 db.UpdateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransfer indicates an expected call of UpdateTransfer.
func (mr *MockStoreMockRecorder) UpdateTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransfer", reflect.TypeOf((*MockStore)(nil).UpdateTransfer), arg0, arg1)
}

// UpsertComicBySlug mocks base method.
func (m *MockStore) UpsertComicBySlug(arg0 context.Context, arg1 db.UpsertComicBySlugParams) (db.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertComicBySlug", arg0, arg1)
	ret0, _ := ret[0].(db.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertComicBySlug indicates an expected call of UpsertComicBySlug.
func (mr *MockStoreMockRecorder) UpsertComicBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertComicBySlug", reflect.TypeOf((*MockStore)(nil).UpsertComicBySlug), arg0, arg1)
}
